#!/bin/bash

for file in *.jpg; do
  mkdir edited
  convert -sharpen 0x1.0 -resize 1024x -quality 80 -font Arial -pointsize 140 -draw "gravity south fill blue text 0,12 'EDITED'" $file edited/$file
done

